FORMAT3 = {
    "ADD": "18",
    "ADDF": "50",
    "AND": "40",
    "COMP": "28",
    "COMPF": "88",
    "DIV": "24",
    "DIVF": "64",
    "J": "3C",
    "JEQ": "30",
    "JGT": "34",
    "JLT": "38",
    "JSUB": "48",
    "LDA": "00",
    "LDB": "68",
    "LDCH": "50",
    "LDF": "70",
    "LDL": "08",
    "LDS": "6C",
    "LDT": "74",
    "LDX": "04",
    "LPS": "D0",
    "MUL": "20",
    "MULF": "60",
    "OR": "44",
    "RD": "D8",
    "RSUB": "4C",
    "SSK": "EC",
    "STA": "0C",
    "STB": "78",
    "STCH": "54",
    "STF": "80",
    "STI": "D4",
    "STL": "14",
    "STS": "7C",
    "STSW": "E8",
    "STT": "84",
    "STX": "10",
    "SUB": "1C",
    "SUBF": "5C",
    "TD": "E0",
    "TIX": "2C",
    "WD": "DC"
}
FORMAT1 = {
    "FIX": "C4",
    "FLOAT": "C0",
    "HIO": "F4",
    "NORM": "C8",
    "SIO": "F0",
    "TIO": "F8"
}
FORMAT2 = {
    "ADDR": "90",
    "CLEAR": "B4",
    "COMPR": "A0",
    "DIVR": "9C",
    "MULR": "98",
    "RMO": "AC",
    "SHIFTL": "A4",
    "SHIFTR": "A8",
    "SUBR": "94",
    "SVC": "B0",
    "TIXR": "B8"
}

# print(FORMAT2["ADDR"])
